export {default as Home} from './home'
export {default as ProductDetails} from './productDetails'
export {default as Product} from './product'
export {default as CategoryList} from './categories/categoryList'
export {default as MainShop} from './shop/mainShop'
export {default as LocationPage} from './location/map'
export {default as Signup} from './auth/signup'
export {default as Login} from './auth/login'
export {default as ForgetPassword} from './auth/forgetPassword'
export {default as ResetPassword} from './auth/resetPassword'
export {default as Contact} from './contact'
export{default as Cart} from './cart'
export {default as CheckOut} from './checkout'
export {default as Profile} from './profile'
export {default as Splash} from './splash'
export {default as Wishlist} from './wishlist'
export {default as Search} from './search'
export {default as Order} from './order'
export {default as Static} from './static'
export {default as SocialLinks} from './socialLinks'

